/* Generated by CIL v. 1.7.4 */
/* print_CIL_Input is false */

#line 1 "/root/patron-artifact-new/patron/test/donors/example01/patch/main.c"
int main(void) 
{ 
  char a ;
  int __cil_tmp2 ;
  char b ;
  int __cil_tmp4 ;
  char x ;
  char y ;
  char c ;

  {
  {
#line 3
  __cil_tmp2 = getchar();
#line 3
  a = (char )__cil_tmp2;
#line 4
  __cil_tmp4 = getchar();
#line 4
  b = (char )__cil_tmp4;
#line 7
  x = a;
#line 8
  y = b;
  }
#line 10
  if ((int )x * (int )y > 127) {
#line 11
    return (1);
  }
#line 13
  c = (char )((int )x * (int )y);
#line 15
  return (0);
}
}
