/* Generated by CIL v. 1.7.4 */
/* print_CIL_Input is false */

#line 1 "/root/patron-artifact-new/patron/test/donors/mini-sam2p/patch/main.c"
int main(void) 
{ 
  char *filename ;
  int __cil_tmp2 ;
  unsigned char buffer[64] ;
  int fd ;
  int __cil_tmp5 ;
  long biWidth ;
  short biBitCnt ;
  int rowbytes ;
  void *bitmap ;
  int __cil_tmp10 ;

  {
  {
#line 3
  __cil_tmp2 = input();
#line 3
  filename = (char *)__cil_tmp2;
#line 5
  __cil_tmp5 = fopen(filename, "rb");
#line 5
  fd = __cil_tmp5;
#line 6
  fread((unsigned char *)buffer, 18, 1, fd);
#line 7
  unnecessary((unsigned char *)buffer, 4, fd);
#line 8
  biWidth = (long )((((int )buffer[0] | ((int )buffer[1] << 8)) | ((int )buffer[2] << 16)) | ((int )buffer[3] << 24));
#line 9
  biBitCnt = (short )((int )buffer[10] | ((int )buffer[11] << 8));
  }
  {
#line 12
  rowbytes = (int )(biWidth * (long )biBitCnt);
#line 13
  __cil_tmp10 = malloc((unsigned long )rowbytes);
#line 13
  bitmap = __cil_tmp10;
  }
#line 14
  return (0);
}
}
