name: check

on: [push, pull_request]

jobs:
  check:
    name: check-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.1

      - name: Install dependencies
        run: opam install ocamlformat.0.24.1

      - name: Check format
        run:
          eval $(opam env)
          script/check-format

      - name: Use cached dependencies
        id: cache-opam
        uses: actions/cache@v3
        env:
          cache-name: cache-opam
        with:
          path: ~/.opam
          key: ${{ env.cache-name }}-build-${{ hashFiles('build.sh') }}
          restore-keys: |
            ${{ env.cache-name }}-build-${{ hashFiles('build.sh') }}
